### ISSUE TITLE
how can i make the ias-ra-data ?

### ISSUE THREAD

**Issue by FolloWinds** [intel/sgx-ra-sample#14]
I dont know how to make it.   
I have sent a email to intel for certificate ,but i got a response  is:
  
Thank you for contacting Intel® Trusted Services Infrastructure. We have opened case #50288 to address your request. 

In order to move forward with your request please respond to this email with your certificate as an attachment (in .txt format).  Please ensure that a common name is included in the certificate.

If you need help with creating this certificate, please visit: 
Creating a Self Signed Certificate 
Certificate Requirements 
.

I dont know where can i get the attachment (in .txt format) , and i cant move forward about it .
please help me , give some suggestions.

**Comment by a5135324** [comment]
You need to create your certificate file and send the certificate to Intel.
For more information, you can see the following link
https://software.intel.com/en-us/articles/certificate-requirements-for-intel-attestation-services

**Comment by FolloWinds** [comment]
https://software.intel.com/en-us/articles/how-to-create-self-signed-certificates-for-use-with-intel-sgx-remote-attestation-using

i follow this to get the certificate(.txt file) ,the intel  forum staff tell  me:

The client.crt file that gets created in Step 6 is the file you need to respond to that email with.  You may need to change the extension from .crt to .txt to be able to send it through correctly.  Once you get you SPID, you will use it along with the client.crt and client.key files in the RA sample code.


whatever i sent the attachment(.txt) to intel , and  i got a reply:
Thank you for contacting Intel® Trusted Services Infrastructure. 

This email is to confirm that we have received the information we need to fulfill your request. It is being processed and will be completed as quickly as possible. Your case number is 50288. 



finally, a day after ,i still not get my reply.
