### ISSUE TITLE
how can i do about the Problem with the local SSL certificate?Could not query IAS

### ISSUE THREAD

**Issue by FolloWinds** [intel/sgx-ra-sample#15]
I wan to run the offical remote attestation example(sgx-ra-example),but the server output is an error:

---- IAS sigrl HTTP Request ------------------------------------------------
HTTP GET https://test-as.sgx.trustedservices.intel.com/attestation/sgx/v3/sigrl/0...
----------------------------------------------------------------------------
* Could not resolve proxy: proxy-us.intel.com
* Closing connection 0
Could not query IAS
could not retrieve the sigrl
error processing msg1
Waiting for a client to connect...

 

another ra example output:

1546485734 INFO  : Received extended EPID group ID: 0
1546485734 INFO  : Serialization successful
1546485734 INFO  : Send to client
1546485734 INFO  : MSG1 received
1546485734 INFO  : Retrieving SigRL from IAS
1546485736 INFO  : curl_easy_perform() failed: Problem with the local SSL certificate

1546485736 INFO  :     Response status is: 0
1546485736 INFO  :     Content-Length: 0
1546485736 INFO  : Error, processing MSG1 failed
1546485736 INFO  : Close connection
1546485736 INFO  : Remote attestation done
 

I follow the offical course to get the local SSL certificate:
https://software.intel.com/en-us/articles/how-to-create-self-signed-cert...

my local SSL certificate  has been validated：
https://software.intel.com/en-us/articles/certificate-requirements-for-i...

I hope someone can give me some suggestions.

**Comment by dtzimmerman** [comment]
You can start by updating the 'settings' file to disable the use of a proxy by setting with the following or if you require a proxy to reach external web services, update the statement to reflect your proxy: 

# IAS_PROXY_URL=

The proxy config statement in the current settings file is incorrect and will be updated soon.

**Comment by jmechalas** [comment]
Closing do to no feedback from after 6 months.
