### ISSUE TITLE
when i executed then run-client cmd, i got sgx_ra_get_msg1: 0000400a,why?

### ISSUE THREAD

**Issue by zhq0918** [intel/sgx-ra-sample#16]
when i run_client , I get the message "sgx_ra_get_msg1: 0000400a",why? my os is ubuntu 16.04,and i check the aesmd status ,as flows:
[ADMIN]EPID Provisioning failed due to network error
and I check the proxy of aesm,as flows:
    #empty line with comment
#proxy type    = direct #direct type means no proxy used
proxy type    = default #system default proxy
#proxy type    = manual #aesm proxy should be specified for manual proxy type
#aesm proxy    = http://proxy_url:proxy_port
#whitelist url = http://sample_while_list_url/
my os accessed the network no problem.

**Comment by zhq0918** [comment]
And I after i sgx_create_enclave, I executed the function which name sgx_init_quote, I got the same error,0x400a, and I checked the sdk manual, its said:"The requested service is temporarily not available",how can i resolve the problem,thanks.

**Comment by jmechalas** [comment]
It looks like your Ubuntu OS doesn't have a system-wide proxy set up. You can do one of two things:

1. Explicitly set the proxy for AESM using "proxy type = direct" and "aesm proxy = "

1. Set your proxy variables in /etc/environment and /etc/bash.bashrc, then reboot to ensure the root account picks up the changes.

**Comment by zhq0918** [comment]
hi,@jmechalas,thank you give me an answer.now I have set the proxy in /etc/environment and /etc/bash.bashrc, and I reboot my host, I checked the env variable right,and  i tried "wget www.baidu.com" ,I can access the internet right. but when i run the client, I got the same error that the requested service is temporarily not available. I checked the aesmdstatus with "systemctl status aesmd",the detail information as flows:
root@sgxvm:/opt/zhqsgx/myDemo/sgx-ra-zhq# **sudo systemctl status aesmd**
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since 五 2019-01-18 22:32:11 CST; 10min ago
  Process: 3650 ExecStart=/opt/intel/libsgx-enclave-common/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 3648 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 3645 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 3642 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 3637 ExecStartPre=/opt/intel/libsgx-enclave-common/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
 Main PID: 3652 (aesm_service)
   CGroup: /system.slice/aesmd.service
           └─3652 /opt/intel/libsgx-enclave-common/aesm/aesm_service

1月 18 22:32:11 sgxvm jhi[3652]: JHI init failed. Status: 768
1月 18 22:32:11 sgxvm jhi[3652]: JHI init at server side failed
1月 18 22:32:11 sgxvm jhi[3652]: JHI init failed. Status: 768
1月 18 22:32:11 sgxvm jhi[3652]: JHI init at server side failed
1月 18 22:32:11 sgxvm jhi[3652]: JHI init failed. Status: 768
1月 18 22:32:11 sgxvm aesm_service[3652]: [ADMIN]Platform Services initializing
1月 18 22:32:11 sgxvm aesm_service[3652]: [ADMIN]Platform Services initialization failed due to DAL error
1月 18 22:33:18 sgxvm aesm_service[3652]: [ADMIN]EPID Provisioning initiated
**1月 18 22:35:32 sgxvm aesm_service[3652]: [ADMIN]EPID Provisioning failed due to network error**
1月 18 22:41:29 sgxvm aesm_service[3652]: [ADMIN]White List update failed due to network error

I think there must be a problem with network configuration,but I don't know,Are there any other configurations to check? Thanks a lot.

**Comment by jmechalas** [comment]
What is in your /etc/aesmd.conf file?

**Comment by zhq0918** [comment]
Thanks @jmeChalas,I have resolved the problem. I changed the /etc/aesms.conf as flows:
#Line with comments only
	  #empty line with comment
#proxy type    = direct #direct type means no proxy used
#proxy type    = default #system default proxy
proxy type    = manual #aesm proxy should be specified for manual proxy type
aesm proxy    = http://XXXX:XXXX=@proxy.XXXX.com:8080
#whitelist url = http://sample_while_list_url/

Thanks a lot.
