### ISSUE TITLE
sgx_rsa_proc_msg2 return SGX_ERROR_INVALID_SIGNATURE

### ISSUE THREAD

**Issue by chilogen** [intel/sgx-ra-sample#18]
when i run this sample code , the client call sgx_ra_proc_msg2 and return SGX_ERROR_INVALID_SIGNATURE. I had read [SGX ERROR CODE](https://software.intel.com/en-us/sgx-sdk-dev-reference-error-codes). The only explain of this error is "The signature is invalid", but which signature(signature for signing Encalve or signature for server msg2)? And how can i make it valid?
  I try to re-genrate Envlabe_private.pem, but problem still there, and i can run others sample code in the SGX SDK correctly.

**Comment by chilogen** [comment]
the signature is msg2.sign_ga_gb?

**Comment by jmechalas** [comment]
This signature it's referring to is the signature of Msg2 which is sent by the service provider ([see the documentation on Msg 3](https://software.intel.com/en-us/articles/code-sample-intel-software-guard-extensions-remote-attestation-end-to-end-example#inpage-nav-4-3-4)), specifically Table 2. It's hard to say whether the server is generating an invalid signature, or the client is not correctly validating it.

What OS are your client and server running? Can you please set VERBOSE=1 and DEBUG=1 on both the client and server configs, then attach sp.log and client.log? **Be sure to remove any password strings for your user certificate from sp.log before attaching.**

**Comment by jmechalas** [comment]
Closing this since we've not received a response since Feb.
