### ISSUE TITLE
Could not query as.sgx.trustedservices.intel.com

### ISSUE THREAD

**Issue by batyrchary** [intel/sgx-ra-sample#23]
Hello 

I tried to measure overhead of remote attestation, which is really low when SigRL and report comes from   "test-as.sgx.trustedservices.intel.com" 

But as I understood, on real production environment it will come from "as.sgx.trustedservices.intel.com"

When I set both  IAS_SERVER_DEVELOPMENT_HOST and IAS_SERVER_PRODUCTION_HOST in iasrequest.h file to as.sgx.trustedservices.intel.com so that results will come from as.sgx.trustedservices.intel.com, I received error shown below.

---- IAS sigrl HTTP Request ------------------------------------------------
HTTP GET https://as.sgx.trustedservices.intel.com/attestation/sgx/v3/sigrl/00000b12
----------------------------------------------------------------------------
*   Trying 34.239.66.92...
* Connected to as.sgx.trustedservices.intel.com (34.239.66.92) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: C:\Program Files\cURL\bin\curl-ca-bundle.crt
  CApath: none
* Unknown SSL protocol error in connection to as.sgx.trustedservices.intel.com:443
* Closing connection 0
Could not query IAS
could not retrieve the sigrl
error processing msg1
Waiting for a client to connect...
 

My questions are: 

how can I get report from real IAS not from testing environment?
aslo what is the time overhead of basic remote attestation ?

Thanks

**Comment by jsraynor** [comment]
Hello.

In order to utilize Intel's production IAS servers, you would have to submit and have approved an SGX Commercial License.  That is the only path to get your certs into the production backend.

https://software.intel.com/en-us/sgx/request-license

Regards.

Scott

**Comment by batyrchary** [comment]
Thanks
