### ISSUE TITLE
API web replacing certificate scheme from Intel side

### ISSUE THREAD

**Issue by Ruide** [intel/sgx-ra-sample#24]
Hi Sir/Madam,

I used to use x.509 certificate to apply for remote attestation. However, currently when I check the application for EPID again, it changed. Now it use API web. Does this mean this ra sample is not supported in the future and i should write my own code to perform remote attestation?

Thanks!
Rd

**Comment by jmechalas** [comment]
We are nearly finished with the updates to the code sample that will support the API key approach. I expect it to take 2-3 weeks for the code to be completed and clear our internal review process.

**Comment by jmechalas** [comment]
The code is complete and has gone through testing. The OK for final release should be coming in the next few days.

**Comment by jmechalas** [comment]
v3.0 has been released
