### ISSUE TITLE
sgx-ra-sample make error

### ISSUE THREAD

**Issue by nikhilrbc** [intel/sgx-ra-sample#25]
Hi Folks, any idea how to tackle the following?

~/sgx-ra-sample$ make
make  all-recursive
make[1]: Entering directory '/home/saiadmin/sgx-ra-sample'
Making all in Enclave
make[2]: Entering directory '/home/saiadmin/sgx-ra-sample/Enclave'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/saiadmin/sgx-ra-sample/Enclave'
make[2]: Entering directory '/home/saiadmin/sgx-ra-sample'
gcc -DHAVE_CONFIG_H -I.  -I/home/saiadmin/linux-sgx/linux/installer/bin/sgxsdk/include -fno-builtin-memset -I/opt/openssl/1.1.0i/include    -g -O2 -MT sgx_stub.o -MD -MP -MF .deps/sgx_stub.Tpo -c -o sgx_stub.o sgx_stub.c
In file included from sgx_stub.c:28:0:
/home/saiadmin/linux-sgx/linux/installer/bin/sgxsdk/include/sgx_uae_service.h:280:45: error: unknown type name ‘bool’
                                             bool refresh_att_key,
                                             ^
sgx_stub.c: In function ‘sgx_thread_set_untrusted_event_ocall’:
sgx_stub.c:204:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_set_untrusted_event_ocall(waiter);
         ^
sgx_stub.c: In function ‘exchange_report_ocall’:
sgx_stub.c:216:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_exchange_report_ocall(sid, dh_msg2, dh_msg2_size, dh_msg3, dh_m
         ^
sgx_stub.c: In function ‘create_session_ocall’:
sgx_stub.c:324:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_create_session_ocall(sid, dh_msg1, dh_msg1_size, timeout);
         ^
sgx_stub.c: In function ‘sgx_thread_wait_untrusted_event_ocall’:
sgx_stub.c:348:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_wait_untrusted_event_ocall(self);
         ^
sgx_stub.c: In function ‘close_session_ocall’:
sgx_stub.c:396:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_close_session_ocall(sid, timeout);
         ^
sgx_stub.c: In function ‘sgx_thread_setwait_untrusted_events_ocall’:
sgx_stub.c:432:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_setwait_untrusted_events_ocall(waiter, self);
         ^
sgx_stub.c: In function ‘sgx_thread_set_multiple_untrusted_events_ocall’:
sgx_stub.c:456:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_set_multiple_untrusted_events_ocall(waiters, total);
         ^
sgx_stub.c: In function ‘invoke_service_ocall’:
sgx_stub.c:468:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_invoke_service_ocall(pse_message_req, pse_message_req_size, pse
         ^
Makefile:544: recipe for target 'sgx_stub.o' failed
make[2]: *** [sgx_stub.o] Error 1
make[2]: Leaving directory '/home/saiadmin/sgx-ra-sample'
Makefile:578: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/saiadmin/sgx-ra-sample'
Makefile:411: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jmechalas** [comment]
This is due to a bug that was introduced in the [SGX SDK 1.5](https://github.com/intel/linux-sgx/issues/393). For now you can add `typedef int bool` to sgx_stub.c.

**Comment by jmechalas** [comment]
The sample code will account for this bug in the next release (which also adds API key support).

**Comment by nikhilrbc** [comment]
Thanks for your reply, it fixed the build issue. 
The following might be deviating from the topic of this issue. Please lmk if there is another way of reaching out to you.

For the API key support I am guessing we cannot use the key from the dev portal?https://api.portal.trustedservices.intel.com/developer. 

Can we fetch the cert needed for the following:
IAS_CLIENT_CERT_FILE=/path/to/certificate.pem
IAS_REPORT_SIGNING_CA_FILE=/path/to/IASReportSigningCACert.pem

using these APIs listed here: https://api.portal.trustedservices.intel.com/documentation
this might not be its intended use

**Comment by jmechalas** [comment]
Not yet. We are nearly done with an updated code sample that uses the API Key support. I was hoping to get that released next week but that may slip a few days into the week after,

**Comment by nikhilrbc** [comment]
Hi Just following up on this. I created an RSA key following the steps here (and registered it via email with IAS):
https://software.intel.com/en-us/articles/how-to-create-self-signed-certificates-for-use-with-intel-sgx-remote-attestation-using

The server runs fine, but when I run the client I get the following error(looks like its expecting an EC key):
1. Extracted the public key into a PEM file:
./run-client -z -S /home/saiadmin/sgx-ra-sample/ias-certs/demo/spid-file -P /home/saiadmin/sgx-ra-sample/ias-certs/demo/pubkey.pem -N /home/saiadmin/sgx-ra-sample/ias-certs/demo/nonce-file -d localhost:7777
/home/saiadmin/sgx-ra-sample/ias-certs/demo/pubkey.pem: key_to_sgx_ec256: 140083311634240:error:0608308E:digital envelope routines:EVP_PKEY_get0_EC_KEY:expecting a ec key:crypto/evp/p_lib.c:339:

2. using the crt file:
./run-client -z -S /home/saiadmin/sgx-ra-sample/ias-certs/demo/spid-file -P /home/saiadmin/sgx-ra-sample/ias-certs/demo/client.crt -N /home/saiadmin/sgx-ra-sample/ias-certs/demo/nonce-file -d localhost:7777
/home/saiadmin/sgx-ra-sample/ias-certs/demo/client.crt: key_to_sgx_ec256: 140104114480960:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:686:Expecting: PUBLIC KEY
140104114480960:error:0608308E:digital envelope routines:EVP_PKEY_get0_EC_KEY:expecting a ec key:crypto/evp/p_lib.c:339:

Feels like I have gone down the wrong path

**Comment by jmechalas** [comment]
You should not have to supply command-line options to run-client (or run-server) if you put them in your settings file.

Also note that v3.0 of the sample just pushed today. This uses [API keys instead of client certificates](https://api.portal.trustedservices.intel.com/) per the latest specification for Intel® SGX Attestation Service Utilizing Enhanced Privacy ID (EPID). The API key approach is less frustrating and less error-prone.

**Comment by nikhilrbc** [comment]
Great, thank you. When I ran it without the CLI options I got the following error:
./run-client 
./run-client: line 126: 93893 Killed                  ./client -s $SPID $cl_nonce $cl_pse $flag_linkable $flag_debug $flag_verbose "$@"

The following is the setting file I used: 
QUERY_IAS_PRODUCTION=0
SPID=********************************
LINKABLE=0
RANDOM_NONCE=1
USE_PLATFORM_SERVICES=0
IAS_CLIENT_CERT_FILE=~/sgx-ra-sample/ias-certs/demo/client.crt
IAS_CLIENT_KEY_FILE=~/sgx-ra-sample/ias-certs/demo/client.key
IAS_REPORT_SIGNING_CA_FILE=~/sgx-ra-sample/ias-certs/demo/AttestationReportSigningCACert.pem
IAS_PROXY_URL=
VERBOSE=1
DEBUG=0

I'll try the v3.0 apis meanwhile.

**Comment by nikhilrbc** [comment]
Succeed.
sed -e "s^@MRSIGNER@^`./mrsigner enclave_sigstruct_raw`^" policy.in > policy
./mrsigner: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory

Where is mrsigner looking for libcryptoso.1.1? I see it in -L/opt/openssl/1.1.0i/lib but it doesn't seem to be reading it from there even though the makefile combines the executables using:
-L/opt/openssl/1.1.0i/lib  -o mrsigner mrsigner.o crypto.o hexutil.o -lcrypto

**Comment by jmechalas** [comment]
It's dynamically loaded, so LD_LIBRARY_PATH needs to be set. That is something that we need to correct in the Makefile.

**Comment by nikhilrbc** [comment]
Thanks for the response. I set it using:
export LD_LIBRARY_PATH=/opt/openssl/1.1.0i/lib
That helped the make process, and the run-server seems to be working.

When I run the run-client I still get the following error:
./run-client -z -S /home/saiadmin/sgx-ra-sample/ias-certs/demo/spid-file -N /home/saiadmin/sgx-ra-sample/ias-certs/demo/nonce-file -d localhost:7777
usage: client [ options ] [ host[:port] ]

Required:
  -N, --nonce-file=FILE    Set a nonce from a file containing a 32-byte
                             ASCII hex string
  -P, --pubkey-file=FILE   File containing the public key of the service
                             provider.
  -S, --spid-file=FILE     Set the SPID from a file containing a 32-byte
                             ASCII hex string
  -d, --debug              Show debugging information
  -e, --epid-gid           Get the EPID Group ID instead of performing
                             an attestation.
  -l, --linkable           Specify a linkable quote (default: unlinkable)
  -m, --pse-manifest       Include the PSE manifest in the quote
  -n, --nonce=HEXSTRING    Set a nonce from a 32-byte ASCII hex string
  -p, --pubkey=HEXSTRING   Specify the public key of the service provider
                             as an ASCII hex string instead of using the
                             default.
  -q                       Generate a quote instead of performing an
                             attestation.
  -r                       Generate a nonce using RDRAND
  -s, --spid=HEXSTRING     Set the SPID from a 32-byte ASCII hex string
  -v, --verbose            Print decoded RA messages to stderr
  -z                       Read from stdin and write to stdout instead
                             connecting to a server.

One of --spid OR --spid-file is required for generating a quote or doing
remote attestation.


Should it be using the keys to fetch these? Sorry if this a dumb question

**Comment by jmechalas** [comment]
You are providing the -z option, which says to use STDIN/STDOUT for the messages, and a server connection address of localhost:7777. You can't do both: either it uses STDIN/STDOUT, or it talks to a server.

**Comment by jmechalas** [comment]
I have pushed a new commit to master that addresses the build issue.

**Comment by nikhilrbc** [comment]
Thanks for that, the build process works now.
Is there a way for you to show an example for running the ./run-client?
The following are the ones I have tried to no avail:

/run-client -v -N /home/saiadmin/sgx-ra-sample/ias-certs/demo/nonce-file -d localhost:7777
./run-client: line 134: 164556 Killed                  ./client -s $SPID $cl_nonce $cl_pse $flag_linkable 
$flag_debug $flag_verbose "$@"

./run-client  -d localhost:7777
./run-client: line 134: 164578 Killed                  ./client -s $SPID $cl_nonce $cl_pse $flag_linkable $flag_debug $flag_verbose "$@"

 ./run-client -S /home/saiadmin/sgx-ra-sample/ias-certs/demo/spid-file -P /home/saiadmin/sgx-ra-sample/ias-certs/demo/pubkey.pem -N /home/saiadmin/sgx-ra-sample/ias-certs/demo/nonce-file -d localhost:7777
/home/saiadmin/sgx-ra-sample/ias-certs/demo/pubkey.pem: key_to_sgx_ec256: 140046524385088:error:0608308E:digital envelope routines:EVP_PKEY_get0_EC_KEY:expecting a ec key:crypto/evp/p_lib.c:339:

The last one looks like I am using the wrong key type, although I created the certificate using the following instructions:
https://software.intel.com/en-us/articles/how-to-create-self-signed-certificates-for-use-with-intel-sgx-remote-attestation-using

**Comment by jmechalas** [comment]
You shouldn't have to provide the -P option to the client. The code contains a pre-generated, hardcoded key that you can override if you choose to, but for demo purposes you shouldn't need to.

What may be tripping you up here is that there are multiple keys involved. There is the public/private key for the service that you are running (in this case, the "sp" utility, executed via run-server), and a public/private key for communicating with IAS if you are using the older, certificate-based authentication.

The link you are pointing at is for the latter: the certificate-based authentication when the server communicates with IAS. If you are using API keys, though, then that goes away and you can ignore it. I suggest you stick with API keys as it is simpler, easier, less error-prone, and the old method will eventually go away.

That leaves the public/private key for the service provider (sp) and attesting client. The point of that key is to guarantee that the client enclave can't be used to communicate with someone else's service provider. You hardcode the private key into the server, and the public key into the client's enclave. Since you can't modify the key without changing the enclave (which, itself, can't be modified after it's compiled or it won't launch), that "locks" the client in to the matching service provider.

As for what that key is, if you want to change it, it is the X and Y component of a 256-bit EC key. It has the following structure:
```
typedef struct _sgx_ec256_public_t
{
    uint8_t gx[SGX_ECP256_KEY_SIZE];
    uint8_t gy[SGX_ECP256_KEY_SIZE];
} sgx_ec256_public_t;
```

The key coordinates must be in little-endian byte order.

I suggest not overriding the keys for the client or server until you get the sample working as-is. You really should not have to provide additional options to run-client or run-server once you have updated the settings file with your SPID and API keys.

**Comment by nikhilrbc** [comment]
Ahh I see, thank you for the explanation appreciate it.
The sample is working now :) 
Just need to update the CPU microcode getting the GROUP_OUT_OF_DATE error.
Is this the best way to do that: 
https://usn.ubuntu.com/3977-1/

**Comment by tomtau** [comment]
I've failed to build the latest master (with SDK 2.6) -- got a different error (not about bool):
```
gcc -DHAVE_CONFIG_H -I.  -I/opt/intel/sgxsdk/include -fno-builtin-memset    -g -O2 -MT sgx_stub.o -MD -MP -MF .deps/sgx_stub.Tpo -c -o sgx_stub.o sgx_stub.c
sgx_stub.c: In function ‘invoke_service_ocall’:
sgx_stub.c:251:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_invoke_service_ocall(pse_message_req, pse_message_req_size, pse_message_resp, pse_message_resp_size, timeout);
         ^
sgx_stub.c: In function ‘sgx_thread_setwait_untrusted_events_ocall’:
sgx_stub.c:275:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_setwait_untrusted_events_ocall(waiter, self);
         ^
sgx_stub.c: In function ‘close_session_ocall’:
sgx_stub.c:299:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_close_session_ocall(sid, timeout);
         ^
sgx_stub.c: At top level:
sgx_stub.c:350:14: error: conflicting types for ‘sgx_select_att_key_id’
 sgx_status_t sgx_select_att_key_id(const uint8_t *p_att_key_id_list, uint32_t att_key_id_list_size, sgx_att_key_id_t **pp_selected_key_id)
              ^~~~~~~~~~~~~~~~~~~~~
In file included from sgx_stub.c:47:0:
/opt/intel/sgxsdk/include/sgx_uae_service.h:247:21: note: previous declaration of ‘sgx_select_att_key_id’ was here
 sgx_status_t SGXAPI sgx_select_att_key_id(const uint8_t *p_att_key_id_list, uint32_t att_key_id_list_size,
                     ^~~~~~~~~~~~~~~~~~~~~
sgx_stub.c: In function ‘create_session_ocall’:
sgx_stub.c:395:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_create_session_ocall(sid, dh_msg1, dh_msg1_size, timeout);
         ^
sgx_stub.c: In function ‘sgx_thread_wait_untrusted_event_ocall’:
sgx_stub.c:503:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_wait_untrusted_event_ocall(self);
         ^
sgx_stub.c: At top level:
sgx_stub.c:530:14: error: conflicting types for ‘sgx_init_quote_ex’
 sgx_status_t sgx_init_quote_ex(const sgx_att_key_id_t *p_att_key_id, sgx_target_info_t *p_qe_target_info, uint8_t refresh_att_key, size_t *p_pub_key_id_size, uint8_t *p_pub_key_id)
              ^~~~~~~~~~~~~~~~~
In file included from sgx_stub.c:47:0:
/opt/intel/sgxsdk/include/sgx_uae_service.h:305:21: note: previous declaration of ‘sgx_init_quote_ex’ was here
 sgx_status_t SGXAPI sgx_init_quote_ex(const sgx_att_key_id_t* p_att_key_id,
                     ^~~~~~~~~~~~~~~~~
sgx_stub.c: In function ‘sgx_thread_set_untrusted_event_ocall’:
sgx_stub.c:563:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_set_untrusted_event_ocall(waiter);
         ^
sgx_stub.c: In function ‘sgx_thread_set_multiple_untrusted_events_ocall’:
sgx_stub.c:599:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_sgx_thread_set_multiple_untrusted_events_ocall(waiters, total);
         ^
sgx_stub.c: In function ‘exchange_report_ocall’:
sgx_stub.c:611:9: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  return (int) p_exchange_report_ocall(sid, dh_msg2, dh_msg2_size, dh_msg3, dh_msg3_size, timeout);
         ^
Makefile:569: recipe for target 'sgx_stub.o' failed
```

**Comment by nikhilrbc** [comment]
Hi Tom,
The bool error I got was from an earlier commit in master.
For the error you are facing you'll have to modify sgx_stub.c:
1. comment out  //#include <sgx_uae_service.h>
2. import 
#include "sgx_quote.h"
#include "sgx_error.h"
#include "sgx_urts.h"

Its funny cuz sgx_stub.c is just implementing those functions.
Hope this works for you.

**Comment by jmechalas** [comment]
FYI, sgx_stub.c is just a set of dynamic loading stubs. This is what allows the finished binary to exit gracefully instead of spit out shared library errors if it's run on a system without the SGX runtime.

I'll examine the build for the 2.6 SDK. It's supposed to be detecting whether bool is used in sgx_uae_service.h to deal with the 2.5 SDK, but there must be something wrong in that logic.

**Comment by jmechalas** [comment]
The SGX SDK v2.6 removed a parameter from sgx_init_quote_ex() which is causing this to break.

**Comment by jmechalas** [comment]
I pushed a commit to master that should resolve this for the 2.6 SDK

**Comment by tomtau** [comment]
It works fine now, thanks!

I guess this issue can be closed.
