### ISSUE TITLE
MIssing flag when building mrsigner

### ISSUE THREAD

**Issue by gsoligna** [intel/sgx-ra-sample#26]
Hello,

I have been trying build the project after the new release : after having done

```
./bootstrap
./configure --with-openssl-dir=good_path
make
```

just like the README indicates, I had undefined references to openssl functions when the Makefile hit
`g++ -std=c++11  -g -O2 -L/home/xxx/sgxsdk/lib64 -L/opt/openssl/1.1.0i/lib  -o mrsigner mrsigner.o crypto.o hexutil.o`.

I have been able to build by adding the `-lcrypto` flag, so maybe you forgot to update a file related to the build ?

*Built with Ubuntu 18.04 and Linux SDK 2.5

**Comment by jmechalas** [comment]
You are correct. Looks like I messed up when resolving a merge conflict. I'll get this fix pushed out.

**Comment by jmechalas** [comment]
Added this flag to Makefile.am. It seems this only happens when you have to use --with-openssl-dir so there's probably a bug in the configure script somewhere, but this quick change doesn't hurt anything and gets it working until I can take the time to dig into the root of the problem.
