### ISSUE TITLE
Error 400 from IAS for Quote Attestation Request 

### ISSUE THREAD

**Issue by hello31337** [intel/sgx-ra-sample#27]
Hi,

I'm developing some system whose remote attestation part is based on this sample.
I'm using relatively old version of this sample (the one which doesn't support API key request for IAS).

At least until few days ago, every thing works well. But today I ran my system (whose remote attestation part is the same as this repository's older one), I got some error.

This error happens when I send Quote to IAS, and the error is like this:

```
* upload completely sent off: 1512 out of 1512 bytes
< HTTP/1.1 400 Bad Request
< request-id: db7c3d5ae1584f178700b56e0dc76311
< Content-Length: 0
< date: Tue, 09 Jul 2019 10:44:58 GMT
< Connection: keep-alive
<
* Connection #0 to host test-as.sgx.trustedservices.intel.com left intact

---- IAS report HTTP Response ----------------------------------------------
HTTP/1.1 400 Bad Request
request-id: db7c3d5ae1584f178700b56e0dc76311
Content-Length: 0
date: Tue, 09 Jul 2019 10:44:58 GMT
Connection: keep-alive


----------------------------------------------------------------------------
attestation query returned 400:
Invalid payload
Attestation failed
error processing msg3
```

I'm sure that I have been used IAS v3, so it is hard that the cause of this error is deprecation of IAS v2.

And I confirmed that designation of linkable/unlinkable is correct, and SPID is also correct.

If you know, would you tell me the possible cause of this error?

OS is Ubuntu18.04, and the version of SGXSDK is 2.6.

**Comment by jmechalas** [comment]
I think what's happening here is that the earlier builds of the sample didn't set the content-type in the request to application/json per the API spec, and IAS is rejecting it as a non-compliant request.

Which version of the RA sample are you using?

**Comment by hello31337** [comment]
Thanks for your response.

I cloned this repository on Nov., 2018, so I think the version of RA sample which I use is v2.2.2.

I know I should eventually update my system to use v3.0 RA sample, but unfortunately I have to record some demo movie as soon as possible now.

So if there are some hot fix for this symptom, I really appreciate If you could tell me (although I still continue to try to find some solution by myself, too).


I'm sorry to bother you, but any advice is appreciated.

(If there is a necessity to look over my code, please see [here](https://github.com/hello31337/BI-SGX). )

**Comment by hello31337** [comment]
After that, I managed to modify my codes to use newer (v3.0) RA sample code.
So far it seems that this modification works well.

Sorry for bothering you.
