### ISSUE TITLE
Sp Could not query IAS

### ISSUE THREAD

**Issue by Kyrios0** [intel/sgx-ra-sample#3]
Hi.

I'm trying to run remote attestation end to end example on Windows 10 64-bit

But I met a error after sever sending IAS sigrl HTTP Request: **Could not query IAS.**

I got SPID from https://software.intel.com/en-us/form/sgx-onboarding.

I used my self-signed certificate(*.crt) as RA_IAS_CLIENT_CERT_FILE, which I made by following https://software.intel.com/en-us/articles/how-to-create-self-signed-certificates-for-use-with-intel-sgx-remote-attestation-using

And I used AttestationReportSigningCACert.pem as RA_IAS_REPORT_SIGNING_CA_FILE which got from https://software.intel.com/sites/default/files/managed/7b/de/RK_PUB.zip.

Is my certificate wrong?

here is my sample output: https://pastebin.com/P4y62sCq

Thanks for any help!

**Comment by dtzimmerman** [comment]
Hi Kyrios0,

I'm currently investigating and seeing a similar issue.  In your case you are likely timing out when the server attempts to contact the IAS for the SigRL.  You can verify if you define the following in your settings.cmd file:

::======================================================================
:: Debugging options
::======================================================================

:: Set to non-zero for verbose output

SET RA_VERBOSE=1

:: Set to non-zero for debugging output

SET RA_DEBUG=1

**Comment by Kyrios0** [comment]
Thanks for all replying...
I tested the code with DEBUG mode. It looks like my network was OK but my certificate was wrong.
Recently I lost my working PC for some reason so I can't continue my project in a short time...
Thanks to dtzimmerman again.

**Comment by dtzimmerman** [comment]
@ndokmai Did enabling RA_VERBOSE or RA_DEBUG mode in the settings.cmd file provide you with any additional information?  My issue was that I wasn't properly specifying the private key file (IAS_CLIENT_KEY_FILE option), nor the password to the private key (IAS_CLIENT_CERT_KEY_PASSWORD_FILE option) in the settings.cmd file.

**Comment by dtzimmerman** [comment]
Ok.  Will close the issue now.  If you still have issues after on-boarding your updated cert, feel free to re-open or create a new ticket.

**Comment by FolloWinds** [comment]
I met the same problem, how did you do bout it?   my output is the same as you, please give some suggestions.thank you very much,my friend.
