### ISSUE TITLE
Supports for Intel SGX SDK version 2.8

### ISSUE THREAD

**Issue by AmbitionXiang** [intel/sgx-ra-sample#38]
Hi, Intel SGX SDK has updated to version 2.8, with this version of SDK, this sample can not run, would you like to update this sample? Thanks.

**Comment by jmechalas** [comment]
I'll take a look at this in the next couple of days. Thank you for reporting the issue.

**Comment by mechalas** [comment]
Support for the PSE on Linux has been dropped from the 2.8 SDK. It requires the ME, and the full ME software stack has never been actively supported on Linux. To get this to compile, references to platform services need to be removed for the Linux targets. I am going through the code and doing that, and trying to clean up any loose ends as a result.

**Comment by jmechalas** [comment]
I have pushed changes to master that fix builds on Linux under the 2.8 SDK.

**Comment by AmbitionXiang** [comment]
Thank you for pushing changes. There is still a warning in client.cpp. 
/opt/intel/sgxsdk/include/sgx_uae_service.h:36:2: warning: #warning This header is deprecated. Please consider using one of the 3 headers "sgx_uae_launch.h", "sgx_uae_epid.h" and "sgx_uae_quote_ex.h". To disable this warning use -Wno-deprecated. [-Wcpp]
 #warning This header is deprecated. \

**Comment by zavalyshyn** [comment]
Version 2.9 of Intel SDK/PSW has now been released. Current sgx-ra-sample code from a master branch seems to not work with it. 
When I run the client code I get a "This system does not support Intel SGX." error. 

Any plans to support the latest release?

**Comment by mechalas** [comment]
We're discussing what we should do since one of the sample targets for the RA sample is Ubuntu 18, and 2.9 won't build on that platform out of the box due to the binutils version.

**Comment by zavalyshyn** [comment]
> 2.9 won't build on that platform out of the box due to the binutils version.

I'm not sure that's still a case. I have just compiled and installed the latest Intel SGX/PSW release v2.9 from source on Ubuntu 18.04.4 LTS Bionic. It works fine. I could run the sample code apps.

**Comment by jmechalas** [comment]
I got 2.9 built and installed, and the sample runs on Ubuntu without further changes.

The error you're seeing can occur when the driver is not loaded. If your system had a kernel update, you'll need to recompile and reinstall the driver. You can verify that the driver is loaded using lsmod. If you are using the [out-of-tree driver](https://github.com/intel/linux-sgx-driver) it will show up as isgx:
```
$ lsmod | grep sgx
isgx                   49152  2
```
If you're on a system that supports Flexible Launch Control and are using the DCAP driver, it will be intel_sgx.
```
$ lsmod | grep sgx
intel_sgx              94208  6
```

**Comment by jmechalas** [comment]
Newest release of the sample builds under 2.9
