### ISSUE TITLE
Enclave Trust is NOT TRUSTED and COMPLICATED. The client is out of date

### ISSUE THREAD

**Issue by yyyyyp** [intel/sgx-ra-sample#43]
I wonder if you increases the recommended value of CPU_SVN from 0d0d to 0e0e and what should I do ? As far as I know,  I have got the latest update of bios.

PS.  machine: DELL XPS-13-7390 ubuntu 18.04 Desktop  SGX_SDK 2.9
      cpu_svn     = 0d0effff028000000000000000000000
      Microcode =0xca
      
 PIB:04000f00000e0e02040180060000000000000000000b00000b000000020000000000000b85ab46332eb2d59c305a0698f5f0d2ec006e4be83bf845697d03587879e350af2601ce78e3a1864496eeacd44d837e518523d94ed14d0008552796b2cfa2907996

**Comment by jmechalas** [comment]
THis is almsot certainly the same issue as #42
