### ISSUE TITLE
running service provider code on RISCV

### ISSUE THREAD

**Issue by hadaroren11** [intel/sgx-ra-sample#44]
Hello,
I want to compile the code of the service provider so i can run it on riscv processor, you think its possible ?
The Makefile is very complicated so I’m having hard time to understand what to change and how...
If you have any idea how to help me it will be amazing !
Thanks 🙇‍♀ !

**Comment by jmechalas** [comment]
There are no restrictions on the service provider component, so it should be possible.
The automake configuration in the project is designed to build both the client and service provider. Your best course of action would be to create a separate build just for the service provider component. That's not something I can spend time on doing, but if you are familiar with automake then the sp section of Makefile.am has what you need.
