### ISSUE TITLE
No longer compatible with SGXSDK v2.8 or newer version

### ISSUE THREAD

**Issue by hello31337** [intel/sgx-ra-sample#48]
Hello.

Recently, I Upgraded SGXSDK to v2.9.1, and I noticed that current version of sgx-ra-sample is no longer compatible SGXSDK which version is v2.8 or newer.

This is because sgx_tae_service.h is obsoleted after SGXSDK v.2.8, and current sgx-ra-sample uses several elements of sgx_tae_service.h like sgx_create_pse_session().

When I deleted sgx_tae_service.h-related elements from each sources (every of them are related with pse), sgx-ra-sample was successfully compiled and run.

I think sgx-ra-sample should be upgraded for newer SGXSDK when you have a time (Or did I miss some other solutions for this symptom?).

**Comment by mechalas** [comment]
An update to the sample which removes references to the PSE and bumps the IAS protocol API version to 4 is in progress.
