### ISSUE TITLE
microcode update

### ISSUE THREAD

**Issue by simplelins** [intel/sgx-ra-sample#49]
**Hi，I try to run this sample,and some error as below:**
---- Platform Update Required ----------------------------------------------
The following Platform Update(s) are required to bring this
platform's Trusted Computing Base (TCB) back into compliance:

  * Intel SGX Platform Software needs to be updated to the latest version.
  * The CPU Microcode needs to be updated.  Contact your OEM for a platform
    BIOS Update.

**I try to solve the error about microcode,with those steps,and still trouble, what i show do next?**

**dmesg | grep microcode**
[    0.000000] microcode: microcode updated early to revision 0xd6, date = 2020-04-23
[    1.011728] microcode: sig=0x906ed, pf=0x2, revision=0xd6
[    1.011918] microcode: Microcode Update Driver: v2.2.
grep -E '^(cpu family|model|stepping|microcode)' /proc/cpuinfo | sort -u
cpu family	: 6
microcode	: 0xd6
model		: 158
model name	: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
stepping	: 13

**uname -vr**
5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020

**apt-get install intel-microcode**
Need to get 2,526 kB of archives.
After this operation, 3,073 kB of additional disk space will be used.
Get:1 http://mirrors.tuna.tsinghua.edu.cn/ubuntu bionic-updates/main amd64 intel-microcode amd64 3.20200609.0ubuntu0.18.04.1 [2,526 kB]
Fetched 2,526 kB in 1s (4,256 kB/s)       
Selecting previously unselected package intel-microcode.
(Reading database ... 303434 files and directories currently installed.)
Preparing to unpack .../**intel-microcode_3.20200609.0ubuntu0.18.04.1_amd64.deb** ...
Unpacking intel-microcode (3.20200609.0ubuntu0.18.04.1) ...
Setting up intel-microcode (3.20200609.0ubuntu0.18.04.1) ...
update-initramfs: deferring update (trigger activated)
intel-microcode: microcode will be updated at next boot
Processing triggers for initramfs-tools (0.130ubuntu3.9) ...

**Comment by jmechalas** [comment]
Microcode updates are packaged into BIOS updates that are delivered by your system's OEM. Not all microcode updates can be applied after the system is booted; some must be applied in the pre-boot stage, which is why BIOS updates are required.

Check with your device manufacturer and ensure you are running the most recent BIOS.

**Comment by simplelins** [comment]
yeah,I had installed recently release packaged into BIOS which from dell supportor . as I know ,i had done all the BIOS update and microcode update. 
and for BIOS, what i installed  is Vostro_3471_3671_Inspiron_3471_3671_1.2.0.exe
and for microcode ,what i installed is  intel-microcode_3.20200609.0ubuntu0.18.04.1_amd64.deb.
please not close the issue directly,thanks!

**Comment by jmechalas** [comment]
I cannot provide you with assistance on microcode updates. That's neither my area of expertise nor within scope for this project.
