### ISSUE TITLE
how to verify mr_enclave  

### ISSUE THREAD

**Issue by zhangdilu** [intel/sgx-ra-sample#52]
I want to know why the sample code verify the value of mr_signer but not mr_enclave , As far as I know mr_signer can only represent the hash of public_key. Is there something wrong with my understanding?

**Comment by jmechalas** [comment]
It's really a policy decision. If you are only have one signing key for all your enclaves, then storing multiple MRENCLAVE hashes and checking each might be more of a hassle than simply checking MRSIGNER. In either case you are going to be basing your trust decision on the ISVPRODID, ISVSVN, and the TCB status of the client. (In theory if you know the MRENCLAVE hash then you know ISVPRODID and ISVSVN, but in practice that's becomes a black box so for clarity you're probably going to have the code look at them, anyway).

**Comment by zhangdilu** [comment]
> It's really a policy decision. If you only have one signing key for all your enclaves, then storing multiple MRENCLAVE hashes and checking each might be more of a hassle than simply checking MRSIGNER. In either case you are going to be basing your trust decision on the ISVPRODID, ISVSVN, and the TCB status of the client. (In theory if you know the MRENCLAVE hash then you know ISVPRODID and ISVSVN, but in practice that's a black box, so for clarity you're probably going to have the code look at them, anyway).

Thanks for your timely reply！ However MRSIGNER can not represent the correctness of code and data loaded in SGX,  but represent the people who use the SGX. Similarly, ISVPRODID, ISVSVN can not guarantee it.  But sometimes I just need to verify that the code loaded in SGX is trustworthy, but not the person who sign it. What should I do ?

**Comment by simplelins** [comment]
@zhangdilu   
    hi, we can get the value of mr_enclave at build-time using the command :  sgx_sign dump -enclave enclave.signed.so -dumpfile out.log.  at out.log file, we can checkout  'metadata->enclave_css.body.enclave_hash.m', as below:
`metadata->enclave_css.body.misc_select: 0x0
 75 metadata->enclave_css.body.misc_mask: 0xffffffff
 76 metadata->enclave_css.body.attributes.flags: 0x4
 77 metadata->enclave_css.body.attributes.xfrm: 0x3
 78 metadata->enclave_css.body.attribute_mask.flags: 0xfffffffffffffffd
 79 metadata->enclave_css.body.attribute_mask.xfrm: 0xffffffffffffff1b
 80 metadata->enclave_css.body.enclave_hash.m:                                                                                                  
 81 0xd1 0xfc 0xae 0x7c 0x30 0xe5 0x24 0x54 0x60 0xd7 0x2c 0xd7 0x8f 0x6c 0x8b 0x96•
 82 0x7d 0xfe 0xcc 0x64 0x9d 0xc7 0xec 0xf3 0x71 0xbf 0xec 0x3e 0x31 0x60 0x80 0x1c•
 83 metadata->enclave_css.body.isv_prod_id: 0x0
 84 metadata->enclave_css.body.isv_svn: 0x0
`
then the sp app can get this value at building time, and compare with enclave's  mr_enclave at remote-attestation getting from enclave's quote. 
but i never find a demo using the value to do a verification.

**Comment by zhangdilu** [comment]
> @zhangdilu
> hi, we can get the value of mr_enclave at build-time using the command : sgx_sign dump -enclave enclave.signed.so -dumpfile out.log. at out.log file, we can checkout 'metadata->enclave_css.body.enclave_hash.m', as below:
> `metadata->enclave_css.body.misc_select: 0x0 75 metadata->enclave_css.body.misc_mask: 0xffffffff 76 metadata->enclave_css.body.attributes.flags: 0x4 77 metadata->enclave_css.body.attributes.xfrm: 0x3 78 metadata->enclave_css.body.attribute_mask.flags: 0xfffffffffffffffd 79 metadata->enclave_css.body.attribute_mask.xfrm: 0xffffffffffffff1b 80 metadata->enclave_css.body.enclave_hash.m: 81 0xd1 0xfc 0xae 0x7c 0x30 0xe5 0x24 0x54 0x60 0xd7 0x2c 0xd7 0x8f 0x6c 0x8b 0x96• 82 0x7d 0xfe 0xcc 0x64 0x9d 0xc7 0xec 0xf3 0x71 0xbf 0xec 0x3e 0x31 0x60 0x80 0x1c• 83 metadata->enclave_css.body.isv_prod_id: 0x0 84 metadata->enclave_css.body.isv_svn: 0x0 `
> then the sp app can get this value at building time, and compare with enclave's mr_enclave at remote-attestation getting from enclave's quote.
> but i never find a demo using the value to do a verification.

Thanks very much.  I have a question that how do you determine that a person’s public key is trusted (MRSIGNER is trusted. ). In other words, Whether remote authentication can only be performed between people with known identities.  If you want to pass your private data to an unknown SGX device, if I have verified that its MRENCLAVE value is correct (for example, MRENCLAVE from an official program), I think I can safely pass data to this device after remote authentication. I don't know if my idea is right.

**Comment by zhangdilu** [comment]
@simplelins hi, this problem has bothered me for a long time，I really hope you can give me some guidance.

**Comment by simplelins** [comment]
maybe we can communite with wechat directly, simple0, I can share what i known.

**Comment by zhangdilu** [comment]
> maybe we can communite with wechat directly, simple0, I can share what i known.

你的微信是啥呀哈哈

**Comment by zhangdilu** [comment]
@simplelins 你的微信是啥呀哈哈，不方便的话你先留个邮箱也可以

**Comment by simplelins** [comment]
> @simplelins 你的微信是啥呀哈哈，不方便的话你先留个邮箱也可以

simplelin0
