### ISSUE TITLE
sp.cpp derive_kdk method should use EVP_PKEY as 3rd argument for portability

### ISSUE THREAD

**Issue by ChrisMcConnell** [intel/sgx-ra-sample#6]
The derive_kdk method currently uses sgx_ra_msg1_t as the third argument, then proceeds to parse out msg1 for the Ga key.

int derive_kdk(EVP_PKEY *Gb, unsigned char kdk[16], sgx_ra_msg1_t *msg1, config_t *config)

The derive_kdk method should not be dependent on another data structure and actually derive the KDK from the values needed, instead of parsing the msg1 data structure.

int derive_kdk(EVP_PKEY *Gb, unsigned char kdk[16], EVP_PKEY *Ga, config_t *config)

**Comment by jmechalas** [comment]
I resolved this by passing the sgx_ec_public_key_t instead of sgx_ra_msg1_t.
