### ISSUE TITLE
Does EPID based RA support SGX2 hardware?

### ISSUE THREAD

**Issue by Keepmoving-ZXY** [intel/sgx-ra-sample#73]
Last week, my company get a workstation with SGX2 enabled, below is outout of `cpuid | grep -i sgx`:
```
   Software Guard Extensions (SGX) capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = true
      SGX ENCLV E*VIRTCHILD, ESETCONTEXT     = false
      SGX ENCLS ETRACKC, ERDINFO, ELDBC, ELDUC = false
```
According to Intel's document，SGX2 support DCAP but no clear answer of SGX2 support EPID or not. In my project, EPID based remote attestation is best for us, so does SGX2 support EPID?

**Comment by ScottR-Intel** [comment]
The SGX2 feature bit really only means it supports EDMM (Enclave Dynamic Memory Management).  It doesn't actually mean that it supports DCAP.  For DCAP, you need to have the Flexible Launch Control (aka Launch Config) feature:

cpuid | grep -i sgx
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true

As for EPID support, all consumer CPUs and all Xeon E-xxxx CPUs that support SGX support EPID.  But, our newest 
3rd Generation Intel® Xeon® Scalable Processors (codename Ice Lake Server) and all future Scalables only support DCAP (no EPID support).

**Comment by Keepmoving-ZXY** [comment]
oh, my cpu is `Intel(R) Xeon(R) Platinum 8368 CPU `, it only support DCAP, thank you for your help.
